In [ ]:
import tensorflow as tf

In [ ]:
# initialization of tensors
x= tf.constant(4)
print(x)

tf.Tensor(4, shape=(), dtype=int32)


In [ ]:
x= tf.constant(4, shape=(1,1),dtype=tf.float32)
print(x)

tf.Tensor([[4.]], shape=(1, 1), dtype=float32)


In [ ]:
x= tf.constant([[1,2,3],[4,5,6]])
print(x)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [ ]:
x= tf.ones((3,3))
print(x)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)


In [ ]:
x= tf.zeros((3,3))
print(x)

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]], shape=(3, 3), dtype=float32)


In [ ]:
x= tf.eye(3) # identity matrix
print(x)

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)


In [ ]:
x= tf.random.normal((3,3),mean=0,stddev=1)
print(x)

tf.Tensor(
[[-0.42511263  0.7184938   0.6217764 ]
 [ 0.27269357  0.9483724   0.27814677]
 [-0.5154918  -1.0287124   1.6564116 ]], shape=(3, 3), dtype=float32)


In [ ]:
x= tf.random.uniform((3,3),minval=0,maxval=1)
print(x)

tf.Tensor(
[[0.38675928 0.8319634  0.06631279]
 [0.326195   0.9849602  0.7735878 ]
 [0.11206341 0.00673115 0.11722648]], shape=(3, 3), dtype=float32)


In [ ]:
x= tf.range(start=1,limit=10,delta=2) # delta means step or gap btw each number
print(x)

tf.Tensor([1 3 5 7 9], shape=(5,), dtype=int32)


In [ ]:
# to change data type
tf.cast(x,dtype=tf.float64)

<tf.Tensor: shape=(5,), dtype=float64, numpy=array([1., 3., 5., 7., 9.])>

**Mathematical operations**

In [ ]:
x= tf.constant([1,2,3])
y= tf.constant([4,5,6])

In [ ]:
z=tf.add(x,y)
z=x+y 
print(z)

tf.Tensor([5 7 9], shape=(3,), dtype=int32)


In [ ]:
tf.compat.v1.disable_eager_execution()

# building a computational graph
a=tf.constant(2)
b=tf.constant(4)
c=a+b


print(c)

Tensor("add:0", shape=(), dtype=int32)


In [ ]:
#running a computational graph
ssn = tf.compat.v1.Session()   # tf.compat.v1 module contains the complete TensorFlow 1.x API, with its original semantics.

ssn.run(c)

6

In [ ]:
x1=tf.constant([1,2,4,5])
x2=tf.constant([2,3,4,5])

#result = tf.multiply(x1,x2)
result=x1*x2

print(result)

Tensor("mul_1:0", shape=(4,), dtype=int32)


In [ ]:
 ssn.run(result)

array([ 2,  6, 16, 25], dtype=int32)

**Placeholder : not providing values at the time of declaration but providing values later at the time of execution**

In [ ]:
#a=tf.placeholder(tf.float32)
a= tf.compat.v1.placeholder(tf.float32)
#b=tf.placeholder(tf.float32)
b= tf.compat.v1.placeholder(tf.float32)
c=a+b
c

<tf.Tensor 'add_1:0' shape=<unknown> dtype=float32>

In [ ]:
ssn.run(c,{a:1,b:4})  # assigning values to a abd b here

5.0

**Placeholder is very useful when we want to give different input values**

In [ ]:
ssn.run(c,{a:[1,2,3],b:[4,2,1]})  # assigning values to a abd b here

array([5., 4., 4.], dtype=float32)

In [ ]:
ssn.run(c,{a:[1,2],b:[4,2]})

array([5., 4.], dtype=float32)

In [ ]:
ssn.run(c,{a:1,b:2})

3.0

**Variable**

In [ ]:
#x=tf.Variable([1])
x=tf.compat.v1.Variable([2])

#q=tf.Variable([.1],tf.float32)

#w=tf.Variable([3])
w=tf.compat.v1.Variable([3])
c=x*w
init = tf.compat.v1.global_variables_initializer()

ssn.run(init)
ssn.run(c)

array([6], dtype=int32)